### ISSUE TITLE
Delete has weird memory management behaviour

### ISSUE THREAD

**Issue by jukibom** [CircuitLord/NotReaper#14]
Delete + undo + redo does not delete and allows undo again (invalid state, multiple notes)

Causes null exception for any other redo actions with affectedTargets (redo adds from scratch - delete should maybe move to a temporary bucket or something...?)

**Comment by jukibom** [comment]
Need to actually dig into this and get some concrete "wtf is happened" info in this ticket

**Comment by Mettra** [comment]
If you want to assign this to me, I've started working through this. I'm planning on removing all the references from the undo/redo actions, and just keep enough data to re-find the notes when the action is triggered.
