### ISSUE TITLE
Select + drag targets makes it possible to move outside the grid 

### ISSUE THREAD

**Issue by jukibom** [CircuitLord/NotReaper#15]
This should NOT be a validation step on loading existing files as some maps do have targets outside of the grid using offsets rather than the pitch value.

This only affects the UI of single notes and groups of notes being dragged around and should be prevented in the drag code (unless an override modifier is held? Some people do like to push things out of the grid).

**Comment by jukibom** [comment]
Should this prevent a block of notes being moved if one of the notes would be out of bounds or should it crush the notes up against the side?

**Comment by CircuitLord** [comment]
Mapping outside the grid is now supported.
