### ISSUE TITLE
Improved overlay for targets to be placed

### ISSUE THREAD

**Issue by jukibom** [CircuitLord/NotReaper#36]
The cursor shows an icon of the same style and opacity as the target icons already in the grid / scene. It isn't always obvious that a new icon is about to be placed on click.

Not sure what this should look like, one suggestion by aggrogahu is an inverted style.

![image](https://user-images.githubusercontent.com/5649179/64989224-f2c99e80-d8c4-11e9-82d3-2c4e4494c53a.png)

**Comment by CircuitLord** [comment]
Working on a concept for this, might need some help from our graphics people to make some of the shapes that go in the middle of the target, AKA like on horz/verts, I have the outline textures from the rings of then notes, but that might not be thick enough for some of what we want.
![image](https://user-images.githubusercontent.com/11892359/65088460-151ff280-d97f-11e9-8c63-e66ede84b2f6.png)

**Comment by CircuitLord** [comment]
October hooked me up with some textures, I added them in, and they look good. Gonna work on an animation for switching between them before I push.
