### ISSUE TITLE
Shortcut for hiding grid is shown as H, but N hides the grid

### ISSUE THREAD

**Issue by rolopogo** [CircuitLord/NotReaper#64]
The shortcut menu (F1) lists H to hide the grid, but the function is bound to the N key.
![image](https://user-images.githubusercontent.com/22004359/65387717-c9d06000-dd41-11e9-8bf4-0593a3c317dd.png)

**Comment by jukibom** [comment]
Done in #37e34e44bd7605ec31d12b97f8ca6403027b5215
