### ISSUE TITLE
cues have 0 ticklength

### ISSUE THREAD

**Issue by aggrogahu** [CircuitLord/NotReaper#71]
default ticklength for non sustain cues are currently 0, which creates issues of compatibility with converting back to midi:

![image](https://user-images.githubusercontent.com/27300343/66444219-3c566680-e9f7-11e9-8464-f80ec3c1f097.png)

since the cues will be represented as this tiny hard to see midi notes that are hard to select.

A default of 120 ticklength for regular targets would probably be good. 120 is the equivalent of a sixteenth note, and makes for good visibility in midi editors. In the event that a cue immediately following a cue happens before 120 ticks, this doesn't actually cause any issues with the game or in midi, afaik.

**Comment by jukibom** [comment]
Fixed in 1.0.5
