### ISSUE TITLE
Waveform view on timeline

### ISSUE THREAD

**Issue by bdkuhman** [CircuitLord/NotReaper#72]
I think it would be helpful to be able to see the song waveform in the timeline. Many other editors have this like Moonscraper, and it would help with syncing notes if the bpm or offset is a little off.

**Comment by jukibom** [comment]
This actually used to be in there and I think caused some weird problem. I agree it's worth looking back into but it also should have a visibility toggle - I think for the most part, after syncing the notes it was just visual noise on the timeline.

**Comment by Mettra** [comment]
Added in the 1.2 update
