### ISSUE TITLE
Numeric target position control

### ISSUE THREAD

**Issue by jukibom** [CircuitLord/NotReaper#91]
Originally requested by @Zernys in #86

>Editable target x and y fields to place/move targets numerically. I often want to place targets perfectly 1/2, 1/3 way, 1/4 etc between grid lines. Having to rely on eye balling it off grid and making repeated corrections is time consuming. Also knowing that it is slightly imperfect and off by a pixel or two stresses me out more than I want to admit. This would be less critical with custom grid options, but still a nice feature to have and I expect should be fairly easy to implement.

**Comment by aggrogahu** [comment]
There's a shortcut `ctrl + shift + arrow key` to nudge selected targets by an 1/8th of a grid space.

**Comment by jukibom** [comment]
yeah I'd probably say that satisfies the requirement (unless 1/3 is super important?)
