### ISSUE TITLE
Free-form selection scaling and rotation

### ISSUE THREAD

**Issue by jukibom** [CircuitLord/NotReaper#92]
Originally requested by @Zernys in #86

> The ability to rotate and scale a selection around its center, or even more ideally a movable pivot. Think typical rotation and scaling interactions found in applications like Photoshop.

**Comment by Zernys** [comment]
Even without something as fancy as this, some sort of simple scaling option would be very useful for little development cost. Particularly useful for adapting patterns from higher difficulties to lower difficulties. I ended up writing my own python script to do this directly editing the cues file.

**Comment by aggrogahu** [comment]
rotating and scaling implemented in latest build
